on: [push, pull_request]

name: Build from SVN

concurrency:
  group: ${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 120
    env:
      R_CRAN_WEB: "https://cran.rstudio.com"
      CRAN_RSYNC: 'mirrors.nic.cz::CRAN'
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        script: [ 'check', 'installer' ]
    steps:

    - name: Prepare git
      run: git config --global core.autocrlf false
      shell: bash

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        install: git make perl curl texinfo texinfo-tex rsync unzip diffutils

    - name: "Download rtools43 toolchain"
      run: |
        url="https://github.com/r-windows/files/releases/download/5550/rtools43-toolchain-libs-base-5550.tar.zst"
        curl -sSL $url | tar x --zstd -C /c/ || true
        #echo "RTOOLS43_HOME=c:" >> $GITHUB_ENV
        #echo "R_CUSTOM_TOOLS_SOFT=c:/x86_64-w64-mingw32.static.posix" >> $GITHUB_ENV

    - name: Install Miktex
      shell: powershell
      run: |
        Import-Module .\.github\scripts\installers.ps1
        SetTimezone
        InstallMiktex -ErrorAction SilentlyContinue;

    - name: Build and Check
      run: |
        sed -i.bak 's/rsync -rc/rsync -r/' tools/rsync-recommended
        ./.github/scripts/win-${{matrix.script}}.sh

    - name: Print failed tests
      if: failure() && matrix.script == 'check'
      run: tail -n100 tests/*.fail

    - name: Run Installer
      run: .\src\gnuwin32\installer\R-devel-win.exe /SILENT
      if: matrix.script == 'installer'
      shell: powershell

    - uses: actions/upload-artifact@v3
      with:
        name: installer
        path: src/gnuwin32/installer/R-devel-win.exe
      if: matrix.script == 'installer'
